import argparse
from xml.dom import minidom
import xml.etree.ElementTree as gfg
from xml.dom import minidom

def collect_data_from_standard_file(src_path):
    data = {}
    f = open(src_path, "r")
    for line in f:
        i_name, x, y, w, h, class_name = line.split(',')
        if i_name not in data.keys():
            data[i_name] = []
        data[i_name].append((x, y, w, h, class_name[:-1]))

    return data

def create_xml_from_collected_data(data):
    root = gfg.Element("dataset")

    b1 = gfg.SubElement(root, "name")
    b1.text = "dlib face detection dataset generated by ImgLab"

    b1 = gfg.SubElement(root, "comment")
    b1.text = "This dataset is manually crafted or adjusted using ImgLab web " \
              "tool Check more detail on https://github.com/NaturalIntellige" \
              "nce/imglab"

    m1 = gfg.Element("images")
    root.append(m1)

    for image in data.keys():
        i1 = gfg.SubElement(m1, "image", attrib={'file': image})
        for bbox in data[image]:
            _x, _y, _w, _h, _class = bbox
            b1 = gfg.SubElement(i1, "box", attrib={'top': _y, 'left': _x, 'width': _w, 'height': _h})
            d1 = gfg.SubElement(b1, "label")
            d1.text = _class

    return minidom.parseString(gfg.tostring(root)).toprettyxml(indent="\t")


def main(args):

    collected_data = collect_data_from_standard_file(args.src_path)
    generated_xml = create_xml_from_collected_data(collected_data)
    with open('out.xml', "w") as f:
        f.write(generated_xml)
    # with open('./out.xml', "wb") as files:
    #     generated_xml.write(files)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Convert standard format to '
                                                 'dlib format.')
    parser.add_argument('-src_path', default='./images.txt', type=str,
                        help='Path of the annotation file with standard format '
                             'annotations')
    parser.add_argument('-dest_path', default='./', type=str,
                        help='Path of the folder to store dlib xml annotation f'
                             'ile')
    args = parser.parse_args()

    main(args)